// Auto-generated seed data

import { Seed } from './types'

export const SEEDS: Seed[] = [
  {
    "type": "carbon",
    "name": "Mossroot",
    "level": 1,
    "growthTime": 3,
    "xpGain": 8.0,
    "igcYield": 16,
    "plantEnergy": 2,
    "harvestEnergy": 2,
    "recoveryRate": 1.0,
    "price": 22,
    "levelRequired": 1
  },
  {
    "type": "carbon",
    "name": "Cinderleaf",
    "level": 2,
    "growthTime": 5,
    "xpGain": 13.0,
    "igcYield": 29,
    "plantEnergy": 6,
    "harvestEnergy": 6,
    "recoveryRate": 1.0,
    "price": 40,
    "levelRequired": 2
  },
  {
    "type": "carbon",
    "name": "Fungal Sprout",
    "level": 3,
    "growthTime": 57,
    "xpGain": 22.0,
    "igcYield": 47,
    "plantEnergy": 9,
    "harvestEnergy": 9,
    "recoveryRate": 1.0,
    "price": 65,
    "levelRequired": 3
  },
  {
    "type": "carbon",
    "name": "Emberstalk",
    "level": 4,
    "growthTime": 285,
    "xpGain": 30.0,
    "igcYield": 62,
    "plantEnergy": 15,
    "harvestEnergy": 15,
    "recoveryRate": 0.95,
    "price": 96,
    "levelRequired": 4
  },
  {
    "type": "carbon",
    "name": "Charbloom",
    "level": 5,
    "growthTime": 3420,
    "xpGain": 38.0,
    "igcYield": 78,
    "plantEnergy": 22,
    "harvestEnergy": 22,
    "recoveryRate": 0.9,
    "price": 120,
    "levelRequired": 5
  },
  {
    "type": "carbon",
    "name": "Shadowvine",
    "level": 6,
    "growthTime": 6840,
    "xpGain": 41.0,
    "igcYield": 94,
    "plantEnergy": 29,
    "harvestEnergy": 29,
    "recoveryRate": 0.85,
    "price": 144,
    "levelRequired": 6
  },
  {
    "type": "carbon",
    "name": "Coalberry",
    "level": 7,
    "growthTime": 13680,
    "xpGain": 83.0,
    "igcYield": 164,
    "plantEnergy": 37,
    "harvestEnergy": 37,
    "recoveryRate": 0.8,
    "price": 302,
    "levelRequired": 7
  },
  {
    "type": "carbon",
    "name": "Ashbloom",
    "level": 8,
    "growthTime": 27360,
    "xpGain": 110.0,
    "igcYield": 290,
    "plantEnergy": 41,
    "harvestEnergy": 41,
    "recoveryRate": 0.75,
    "price": 535,
    "levelRequired": 8
  },
  {
    "type": "carbon",
    "name": "Onyx Thistle",
    "level": 9,
    "growthTime": 41040,
    "xpGain": 119.0,
    "igcYield": 377,
    "plantEnergy": 49,
    "harvestEnergy": 49,
    "recoveryRate": 0.7,
    "price": 696,
    "levelRequired": 9
  },
  {
    "type": "carbon",
    "name": "Titanwood",
    "level": 10,
    "growthTime": 82080,
    "xpGain": 230.0,
    "igcYield": 871,
    "plantEnergy": 59,
    "harvestEnergy": 59,
    "recoveryRate": 0.65,
    "price": 2010,
    "levelRequired": 10
  },
  {
    "type": "hydrogen",
    "name": "Dewbud",
    "level": 1,
    "growthTime": 3,
    "xpGain": 17.0,
    "igcYield": 10,
    "plantEnergy": 3,
    "harvestEnergy": 3,
    "recoveryRate": 1.0,
    "price": 18,
    "levelRequired": 1
  },
  {
    "type": "hydrogen",
    "name": "Mistleaf",
    "level": 2,
    "growthTime": 10,
    "xpGain": 29.0,
    "igcYield": 22,
    "plantEnergy": 6,
    "harvestEnergy": 6,
    "recoveryRate": 1.0,
    "price": 40,
    "levelRequired": 2
  },
  {
    "type": "hydrogen",
    "name": "Hydropod",
    "level": 3,
    "growthTime": 300,
    "xpGain": 39.0,
    "igcYield": 33,
    "plantEnergy": 8,
    "harvestEnergy": 8,
    "recoveryRate": 1.0,
    "price": 59,
    "levelRequired": 3
  },
  {
    "type": "hydrogen",
    "name": "Geyserbloom",
    "level": 4,
    "growthTime": 600,
    "xpGain": 48.0,
    "igcYield": 44,
    "plantEnergy": 11,
    "harvestEnergy": 11,
    "recoveryRate": 0.95,
    "price": 88,
    "levelRequired": 4
  },
  {
    "type": "hydrogen",
    "name": "Neptune Reed",
    "level": 5,
    "growthTime": 1800,
    "xpGain": 58.0,
    "igcYield": 61,
    "plantEnergy": 14,
    "harvestEnergy": 14,
    "recoveryRate": 0.9,
    "price": 122,
    "levelRequired": 5
  },
  {
    "type": "hydrogen",
    "name": "Aquafern",
    "level": 6,
    "growthTime": 5400,
    "xpGain": 68.0,
    "igcYield": 73,
    "plantEnergy": 19,
    "harvestEnergy": 19,
    "recoveryRate": 0.85,
    "price": 146,
    "levelRequired": 6
  },
  {
    "type": "hydrogen",
    "name": "Tidefruit",
    "level": 7,
    "growthTime": 14400,
    "xpGain": 117.0,
    "igcYield": 127,
    "plantEnergy": 29,
    "harvestEnergy": 29,
    "recoveryRate": 0.8,
    "price": 305,
    "levelRequired": 7
  },
  {
    "type": "hydrogen",
    "name": "Plasmabud",
    "level": 8,
    "growthTime": 28800,
    "xpGain": 133.0,
    "igcYield": 132,
    "plantEnergy": 33,
    "harvestEnergy": 33,
    "recoveryRate": 0.75,
    "price": 317,
    "levelRequired": 8
  },
  {
    "type": "hydrogen",
    "name": "CryoLily",
    "level": 9,
    "growthTime": 43200,
    "xpGain": 148.0,
    "igcYield": 149,
    "plantEnergy": 43,
    "harvestEnergy": 43,
    "recoveryRate": 0.7,
    "price": 358,
    "levelRequired": 9
  },
  {
    "type": "hydrogen",
    "name": "Stormlotus",
    "level": 10,
    "growthTime": 86400,
    "xpGain": 390.0,
    "igcYield": 495,
    "plantEnergy": 51,
    "harvestEnergy": 51,
    "recoveryRate": 0.65,
    "price": 1485,
    "levelRequired": 10
  },
  {
    "type": "solar",
    "name": "Solgrass",
    "level": 1,
    "growthTime": 3,
    "xpGain": 8.0,
    "igcYield": 12,
    "plantEnergy": 1,
    "harvestEnergy": 1,
    "recoveryRate": 1.0,
    "price": 20,
    "levelRequired": 1
  },
  {
    "type": "solar",
    "name": "Flareberry",
    "level": 2,
    "growthTime": 5,
    "xpGain": 16.0,
    "igcYield": 24,
    "plantEnergy": 4,
    "harvestEnergy": 4,
    "recoveryRate": 1.0,
    "price": 40,
    "levelRequired": 2
  },
  {
    "type": "solar",
    "name": "Sunvine",
    "level": 3,
    "growthTime": 60,
    "xpGain": 24.0,
    "igcYield": 36,
    "plantEnergy": 7,
    "harvestEnergy": 7,
    "recoveryRate": 1.0,
    "price": 59,
    "levelRequired": 3
  },
  {
    "type": "solar",
    "name": "Photosynthia",
    "level": 4,
    "growthTime": 300,
    "xpGain": 33.0,
    "igcYield": 73,
    "plantEnergy": 12,
    "harvestEnergy": 12,
    "recoveryRate": 0.95,
    "price": 132,
    "levelRequired": 4
  },
  {
    "type": "solar",
    "name": "Blazelily",
    "level": 5,
    "growthTime": 3600,
    "xpGain": 30.0,
    "igcYield": 85,
    "plantEnergy": 17,
    "harvestEnergy": 17,
    "recoveryRate": 0.9,
    "price": 154,
    "levelRequired": 5
  },
  {
    "type": "solar",
    "name": "Aurora Fern",
    "level": 6,
    "growthTime": 7200,
    "xpGain": 50.0,
    "igcYield": 97,
    "plantEnergy": 20,
    "harvestEnergy": 20,
    "recoveryRate": 0.85,
    "price": 176,
    "levelRequired": 6
  },
  {
    "type": "solar",
    "name": "Inferno Cactus",
    "level": 7,
    "growthTime": 14400,
    "xpGain": 87.0,
    "igcYield": 128,
    "plantEnergy": 30,
    "harvestEnergy": 30,
    "recoveryRate": 0.8,
    "price": 278,
    "levelRequired": 7
  },
  {
    "type": "solar",
    "name": "Solaris Bloom",
    "level": 8,
    "growthTime": 28800,
    "xpGain": 99.0,
    "igcYield": 145,
    "plantEnergy": 35,
    "harvestEnergy": 35,
    "recoveryRate": 0.75,
    "price": 317,
    "levelRequired": 8
  },
  {
    "type": "solar",
    "name": "Heliothorn",
    "level": 9,
    "growthTime": 43200,
    "xpGain": 112.0,
    "igcYield": 164,
    "plantEnergy": 41,
    "harvestEnergy": 41,
    "recoveryRate": 0.7,
    "price": 358,
    "levelRequired": 9
  },
  {
    "type": "solar",
    "name": "Supernova Orchid",
    "level": 10,
    "growthTime": 86400,
    "xpGain": 374.0,
    "igcYield": 544,
    "plantEnergy": 50,
    "harvestEnergy": 50,
    "recoveryRate": 0.65,
    "price": 1485,
    "levelRequired": 10
  }
];
